---
  - name: Create kubernetes iam role
    iam:
      iam_type: role
      name: "{{ kubernetes_iam_profile_role_name }}"
      state: present
      region: "{{ region }}"
  - name: Add auto scaling instance protection policy
    iam_policy:
      iam_type: role
      iam_name: "{{ kubernetes_iam_profile_role_name }}"
      policy_name: "AutoScalingAccess"
      policy_json: "{{ lookup( 'template', 'autoscale-policy.json.j2') }}"
      state: present
  - name: Create rancher AWS policy
    iam_policy:
      iam_type: role
      iam_name: "{{ kubernetes_iam_profile_role_name }}"
      policy_name: "RancherAWSPolicy"
      state: present
      policy_json: "{{ lookup( 'template', 'rancher-policy.json.j2') }}"

