---
  - name: Check if secret exists
    command: kubectl get secret {{ kubernetes_quayio_secret_name }}
    register: get_secret_result
    failed_when: "{{ get_secret_result.stderr != '' and 'NotFound' not in get_secret_result.stderr }}"
  - name: Delete secret if it exists
    command: kubectl delete secret {{ kubernetes_quayio_secret_name }}
    when: "{{ kubernetes_quayio_secret_name in get_secret_result.stdout }}"
  - name: Create secret
    shell: echo "{{ lookup('template', 'rancher-secret.yml', convert_data=False) }}" | kubectl create -f -