---
  rancher_cluster_name: "default"
  rancher_cluster_ami: "{{ default_ubuntu_ami }}"
  rancher_cluster_key_name: "{{ keyName }}"
  rancher_cluster_region: "{{ region }}"
  rancher_cluster_security_group_name: "{{ security_group_name }}"
  rancher_cluster_min_size: 0
  rancher_cluster_max_size: 25
  ancher_cluster_instance_volume_size: 30
  rancher_cluster_asg_default_cooldown: 660 # seconds
  tear_down: false
  rancher_cluster_tear_down: "{{ tear_down }}"
  rancher_cluster_agent_version: v1.2.0

  # If you change this field, you need to bump rancher_cluster_launch_configuration_version
  rancher_cluster_user_data: |
          #!/bin/bash -xe
          exec > /tmp/userdata.log 2>&1

          wget -qO- https://test.docker.com/ | sh

          # Need to get private IP for amazon instances to be able to ping each other
          sudo docker run -d --privileged \
                -e CATTLE_AGENT_IP="$(ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')" \
                -v /var/run/docker.sock:/var/run/docker.sock \
                -v /var/lib/rancher:/var/lib/rancher \
                rancher/agent:{{ rancher_cluster_agent_version }} {{ rancher_cluster_registration_url }}